repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  # --- Linter & Formatter (Ruff) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # --- Static Type Checking (MyPy) ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        entry: venv/bin/mypy
        additional_dependencies: [
          "django-stubs",
          "djangorestframework-stubs"
        ]
        args: ["--ignore-missing-imports"]

  # --- Security Checkers ---
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # --- Django Templates ---
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  # --- Local Hooks ---
  - repo: local
    hooks:
      - id: migrations
        name: check migrations
        entry: venv/bin/python manage.py makemigrations --check --dry-run --no-input
        language: python
        pass_filenames: false
        files: \.py$

      - id: generate_tree
        name: generate tree
        entry: >
          bash -c "tree-generator -o ./auto/project_structure.txt"
        language: system

      - id: file_merger
        name: merge files
        entry: >
          bash -c "file-merger -d ./blog/models -o ./auto/all_models.txt &&
          file-merger -d ./blog/templates -r -o ./auto/all_templates.txt &&
          file-merger -d ./blog/views -o ./auto/all_views.txt"
        language: system
