# Generated by Django 5.2.7 on 2025-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Резервная копия",
                "verbose_name_plural": "Резервные копии БД",
            },
        ),
    ]
