# Generated by Django 5.2.7 on 2025-11-12 08:26

from django.db import migrations, models

import blog.storages


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.FileField(
                blank=True, storage=blog.storages.get_private_storage, upload_to=""
            ),
        ),
    ]
